use std::sync::atomic::Ordering;
use std::time::{Duration, Instant};

use anyhow::Result;
use crossterm::event::{KeyCode, KeyEvent, KeyModifiers, MouseEvent};
use fb_actor::Ctx;
use fb_config::keymap::Key;
use fb_macro::{act, emit, succ};
use fb_shared::{
	data::Data,
	event::{ActionCow, Event, NEED_RENDER},
};
use fb_widgets::input::InputMode;
use tracing::warn;

use crate::file_browser::{Executor, Router, app::App};

// Helper function to format key events into readable shortcut strings
fn format_key_event(key: &KeyEvent) -> String {
	let mut parts = Vec::new();

	// For Char keys, check if Shift is needed (uppercase letters need Shift)
	let is_char = matches!(key.code, KeyCode::Char(_));
	let needs_shift = if let KeyCode::Char(c) = key.code {
		c.is_uppercase() || "!@#$%^&*()_+{}|:\"<>?".contains(c)
	} else {
		false
	};

	if key.modifiers.contains(KeyModifiers::CONTROL) {
		parts.push("Ctrl");
	}

	// Only add Shift if it's not a char, or if it's a char that needs explicit Shift
	if key.modifiers.contains(KeyModifiers::SHIFT) && (!is_char || needs_shift) {
		parts.push("Shift");
	}

	if key.modifiers.contains(KeyModifiers::ALT) {
		parts.push("Alt");
	}

	let key_str = match key.code {
		KeyCode::Char(c) => {
			// Always use uppercase for letters
			if c.is_alphabetic() { c.to_uppercase().to_string() } else { c.to_string() }
		}
		KeyCode::F(n) => format!("F{}", n),
		KeyCode::Backspace => "Backspace".to_string(),
		KeyCode::Enter => "Enter".to_string(),
		KeyCode::Left => "Left".to_string(),
		KeyCode::Right => "Right".to_string(),
		KeyCode::Up => "Up".to_string(),
		KeyCode::Down => "Down".to_string(),
		KeyCode::Home => "Home".to_string(),
		KeyCode::End => "End".to_string(),
		KeyCode::PageUp => "PageUp".to_string(),
		KeyCode::PageDown => "PageDown".to_string(),
		KeyCode::Tab => "Tab".to_string(),
		KeyCode::BackTab => "BackTab".to_string(),
		KeyCode::Delete => "Delete".to_string(),
		KeyCode::Insert => "Insert".to_string(),
		KeyCode::Esc => "Esc".to_string(),
		_ => return "Unknown".to_string(),
	};

	parts.push(&key_str);
	parts.join("+")
}

pub(super) struct Dispatcher<'a> {
	app: &'a mut App,
}

impl<'a> Dispatcher<'a> {
	#[inline]
	pub(super) fn new(app: &'a mut App) -> Self {
		Self { app }
	}

	#[inline]
	pub(super) fn dispatch(&mut self, event: Event) -> Result<()> {
		let result = match event {
			Event::Call(action) => self.dispatch_call(action),
			Event::Seq(actions) => self.dispatch_seq(actions),
			Event::Render(partial) => self.dispatch_render(partial),
			Event::Key(key) => self.dispatch_key(key),
			Event::Mouse(mouse) => self.dispatch_mouse(mouse),
			Event::Resize => self.dispatch_resize(),
			Event::Focus => self.dispatch_focus(),
			Event::Blur => self.dispatch_blur(),
			Event::Paste(str) => self.dispatch_paste(str),
			Event::Timer => self.dispatch_timer(),
		};

		if let Err(err) = result {
			warn!("Event dispatch error: {err:?}");
		}
		Ok(())
	}

	#[inline]
	fn dispatch_call(&mut self, action: ActionCow) -> Result<Data> {
		Executor::new(self.app).execute(action)
	}

	#[inline]
	fn dispatch_seq(&mut self, mut actions: Vec<ActionCow>) -> Result<Data> {
		if let Some(last) = actions.pop() {
			self.dispatch_call(last)?;
		}
		if !actions.is_empty() {
			emit!(Seq(actions));
		}
		succ!();
	}

	#[inline]
	fn dispatch_render(&mut self, partial: bool) -> Result<Data> {
		if partial {
			_ = NEED_RENDER.compare_exchange(0, 2, Ordering::Relaxed, Ordering::Relaxed);
		} else {
			NEED_RENDER.store(1, Ordering::Relaxed);
		}
		succ!()
	}

	#[inline]
	fn dispatch_key(&mut self, key: KeyEvent) -> Result<Data> {
		use crate::input::InputAction;
		use crate::menu::MenuAction;
		use crossterm::event::KeyCode;

		// COMMENTED OUT: Codex TUI integration
		// PRIORITY 0: If Codex TUI is active, forward ALL keys to it (except Ctrl+C for exit and Ctrl+B for toggle)
		// if self.app.bridge.chat_state.show_codex_tui {
		// 	// Allow Ctrl+C to exit the application
		// 	if key.code == KeyCode::Char('c') && key.modifiers.contains(KeyModifiers::CONTROL) {
		// 		crate::exit_animation::show_train_farewell();
		// 		std::process::exit(0);
		// 	}

		// 	// Allow Ctrl+B to toggle back to DX mode
		// 	if key.code == KeyCode::Char('b') && key.modifiers.contains(KeyModifiers::CONTROL) {
		// 		self.app.bridge.chat_state.toggle_codex_tui();
		// 		NEED_RENDER.store(1, Ordering::Relaxed);
		// 		return succ!();
		// 	}

		// 	// Forward ALL other keys directly to ChatWidget (including Enter, arrows, etc.)
		// 	if let Some(codex_widget) = &mut self.app.bridge.chat_state.codex_widget {
		// 		// Call handle_key_event directly on the ChatWidget
		// 		codex_widget.chat_widget.handle_key_event(key);
		// 		// Process any events generated by the key press
		// 		codex_widget.process_events();
		// 		NEED_RENDER.store(1, Ordering::Relaxed);
		// 		return succ!();
		// 	} else {
		// 		// If Codex is not initialized yet, don't process any keys - just wait
		// 		NEED_RENDER.store(1, Ordering::Relaxed);
		// 		return succ!();
		// 	}
		// }

		// PRIORITY 1: Global menu navigation keys - work when menu is visible on ANY screen
		if self.app.bridge.chat_state.show_tachyon_menu {
			// Check if in content viewer mode - Escape closes it
			if self.app.bridge.chat_state.menu.content_viewer_mode {
				if key.code == KeyCode::Esc {
					// Start closing animation (don't call close_content_viewer yet)
					self.app.bridge.chat_state.menu_is_closing = true;
					self.app.bridge.chat_state.menu.pick_closing_effect();
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				// In content viewer mode, only Escape works - ignore other keys
				succ!()
			}

			// Check if we're in recording mode in keyboard shortcuts submenu
			if self.app.bridge.chat_state.menu.recording_mode
				&& self.app.bridge.chat_state.menu.current_submenu == Some(1)
			{
				// Get the selected shortcut index (skip "Back" and "Toggle Recording Mode")
				if let Some(action_index) = self.app.bridge.chat_state.menu.get_selected_shortcut_index() {
					// Format the key press into a shortcut string
					let shortcut = format_key_event(&key);

					// Don't record navigation keys or special menu keys
					if !matches!(
						key.code,
						KeyCode::Up
							| KeyCode::Down
							| KeyCode::PageUp
							| KeyCode::PageDown
							| KeyCode::Home
							| KeyCode::End
							| KeyCode::Esc
							| KeyCode::Enter
							| KeyCode::Char('j')
							| KeyCode::Char('k')
							| KeyCode::Char('g')
							| KeyCode::Char('G')
					) {
						// Update the keyboard shortcut
						self.app.bridge.chat_state.menu.update_keyboard_shortcut(action_index, shortcut);
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
				}
			}

			match key.code {
				KeyCode::Up | KeyCode::Char('k') => {
					self.app.bridge.chat_state.menu.select_prev_menu_item();
					// Apply theme preview if in theme submenu
					if let Some(theme_name) = self.app.bridge.chat_state.menu.get_highlighted_theme_name() {
						self
							.app
							.bridge
							.chat_state
							.apply_theme(&theme_name, self.app.bridge.chat_state.theme_mode);
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::Down | KeyCode::Char('j') => {
					self.app.bridge.chat_state.menu.select_next_menu_item();
					// Apply theme preview if in theme submenu
					if let Some(theme_name) = self.app.bridge.chat_state.menu.get_highlighted_theme_name() {
						self
							.app
							.bridge
							.chat_state
							.apply_theme(&theme_name, self.app.bridge.chat_state.theme_mode);
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::PageUp => {
					self.app.bridge.chat_state.menu.page_up(10);
					// Apply theme preview if in theme submenu
					if let Some(theme_name) = self.app.bridge.chat_state.menu.get_highlighted_theme_name() {
						self
							.app
							.bridge
							.chat_state
							.apply_theme(&theme_name, self.app.bridge.chat_state.theme_mode);
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::PageDown => {
					self.app.bridge.chat_state.menu.page_down(10);
					// Apply theme preview if in theme submenu
					if let Some(theme_name) = self.app.bridge.chat_state.menu.get_highlighted_theme_name() {
						self
							.app
							.bridge
							.chat_state
							.apply_theme(&theme_name, self.app.bridge.chat_state.theme_mode);
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::Home | KeyCode::Char('g') => {
					self.app.bridge.chat_state.menu.jump_to_top();
					// Apply theme preview if in theme submenu
					if let Some(theme_name) = self.app.bridge.chat_state.menu.get_highlighted_theme_name() {
						self
							.app
							.bridge
							.chat_state
							.apply_theme(&theme_name, self.app.bridge.chat_state.theme_mode);
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::End | KeyCode::Char('G') => {
					self.app.bridge.chat_state.menu.jump_to_bottom();
					// Apply theme preview if in theme submenu
					if let Some(theme_name) = self.app.bridge.chat_state.menu.get_highlighted_theme_name() {
						self
							.app
							.bridge
							.chat_state
							.apply_theme(&theme_name, self.app.bridge.chat_state.theme_mode);
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::Char('t') | KeyCode::Char('T') => {
					// Toggle light/dark mode when in theme submenu
					if self.app.bridge.chat_state.menu.current_submenu == Some(0) {
						self.app.bridge.chat_state.toggle_theme_mode();
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
				}
				KeyCode::Enter => {
					// Check if a model selection is made (MODEL:*)
					if let Some(model_id) = self.app.bridge.chat_state.menu.get_selected_model_id() {
						// Select the model
						self.app.bridge.chat_state.select_model(&model_id);
						// Close menu with animation
						self.app.bridge.chat_state.menu_is_closing = true;
						self.app.bridge.chat_state.menu.pick_closing_effect();
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}

					// Check if toggle mode button is selected
					if self.app.bridge.chat_state.menu.is_toggle_mode_selected() {
						// Toggle the theme mode
						self.app.bridge.chat_state.toggle_theme_mode();
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}

					// Check if toggle recording button is selected
					if self.app.bridge.chat_state.menu.is_toggle_recording_selected() {
						// Toggle the recording mode
						self.app.bridge.chat_state.menu.toggle_recording_mode();
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}

					// Get the current theme name before selecting
					let theme_name = self.app.bridge.chat_state.menu.get_selected_theme_name();

					// Select current menu item (enter submenu or execute action)
					let _should_close = !self.app.bridge.chat_state.menu.select_current_item();

					// If we were in theme submenu and selected a theme, just close the menu
					// (theme is already applied from navigation/hover)
					if theme_name.is_some() {
						self.app.bridge.chat_state.menu_is_closing = true;
						self.app.bridge.chat_state.menu.pick_closing_effect();
					}

					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::Esc => {
					// Close model picker if open
					if self.app.bridge.chat_state.show_model_picker {
						self.app.bridge.chat_state.show_model_picker = false;
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}

					// Go back to main menu if in submenu, otherwise close menu
					if self.app.bridge.chat_state.menu.current_submenu.is_some() {
						self.app.bridge.chat_state.menu.go_back_to_main();
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					} else {
						// Close menu
						self.app.bridge.chat_state.menu_is_closing = true;
						self.app.bridge.chat_state.menu.pick_closing_effect();
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
				}
				_ => {}
			}
		}

		// PRIORITY 2: If in animation mode, handle navigation keys but allow typing
		if self.app.bridge.chat_state.animation_mode {
			let all_animations = crate::AnimationType::all();
			let current_anim = all_animations[self.app.bridge.chat_state.current_animation_index];

			// Handle navigation keys based on current screen
			match key.code {
				KeyCode::Left => {
					if current_anim == crate::AnimationType::Splash {
						// From Splash → Go to first carousel animation (Matrix)
						let carousel = crate::AnimationType::carousel_animations();
						// Find Matrix in all_animations
						if let Some(matrix_idx) = all_animations.iter().position(|a| *a == carousel[0]) {
							self.app.bridge.chat_state.current_animation_index = matrix_idx;
						}
					} else if current_anim == crate::AnimationType::Yazi {
						// From Yazi → Go back to Splash
						self.app.bridge.chat_state.current_animation_index = 0;
					} else {
						// In carousel → Navigate to previous carousel animation
						let carousel = crate::AnimationType::carousel_animations();
						if let Some(current_carousel_idx) = carousel.iter().position(|a| *a == current_anim) {
							let prev_carousel_idx = if current_carousel_idx == 0 {
								carousel.len() - 1
							} else {
								current_carousel_idx - 1
							};
							let prev_anim = carousel[prev_carousel_idx];
							// Find this animation in all_animations
							if let Some(idx) = all_animations.iter().position(|a| *a == prev_anim) {
								self.app.bridge.chat_state.current_animation_index = idx;
							}
						}
					}
					self.app.bridge.chat_state.animation_start_time = Some(Instant::now());
					self.app.bridge.chat_state.play_animation_sound(); // Play sound for new animation
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::Right => {
					if current_anim == crate::AnimationType::Splash {
						// From Splash → Go to Yazi (file browser)
						if let Some(yazi_idx) =
							all_animations.iter().position(|a| *a == crate::AnimationType::Yazi)
						{
							self.app.bridge.chat_state.current_animation_index = yazi_idx;
						}
					} else if current_anim == crate::AnimationType::Yazi {
						// From Yazi → Go back to Splash
						self.app.bridge.chat_state.current_animation_index = 0;
					} else {
						// In carousel → Go back to Splash
						self.app.bridge.chat_state.current_animation_index = 0;
					}
					self.app.bridge.chat_state.animation_start_time = Some(Instant::now());
					self.app.bridge.chat_state.play_animation_sound(); // Play sound for new animation
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				KeyCode::Up => {
					// Set current animation as intro animation (only in carousel)
					if current_anim != crate::AnimationType::Splash
						&& current_anim != crate::AnimationType::Yazi
					{
						self.app.bridge.chat_state.intro_animation = current_anim;
						let anim_name = current_anim.name();
						self.app.bridge.chat_state.show_toast(format!("Intro: {}", anim_name));
						NEED_RENDER.store(1, Ordering::Relaxed);
					}
					succ!()
				}
				KeyCode::Down => {
					// Set current animation as outro animation (only in carousel)
					if current_anim != crate::AnimationType::Splash
						&& current_anim != crate::AnimationType::Yazi
					{
						self.app.bridge.chat_state.outro_animation = current_anim;
						let anim_name = current_anim.name();
						self.app.bridge.chat_state.show_toast(format!("Outro: {}", anim_name));
						NEED_RENDER.store(1, Ordering::Relaxed);
					}
					succ!()
				}
				_ => {
					// For other keys, fall through to handle input
					// This allows typing while viewing animations
				}
			}
		}

		// Global '0' key handler - toggle menu overlay on ANY screen
		if key.code == KeyCode::Char('0') {
			if self.app.bridge.chat_state.show_tachyon_menu {
				// Closing menu - pick random closing animation
				self.app.bridge.chat_state.menu_is_closing = true;
				self.app.bridge.chat_state.menu.pick_closing_effect();
			} else {
				// Opening menu - pick random opening animation
				self.app.bridge.chat_state.menu_is_closing = false;
				self.app.bridge.chat_state.show_tachyon_menu = true;
				self.app.bridge.chat_state.menu.pick_opening_effect();
			}

			NEED_RENDER.store(1, Ordering::Relaxed);
			succ!()
		}

		// Global Ctrl+B handler - toggle between Ollama chat and Codex TUI
		// COMMENTED OUT: Codex TUI integration
		// if key.code == KeyCode::Char('b') && key.modifiers.contains(KeyModifiers::CONTROL) {
		// 	self.app.bridge.chat_state.toggle_codex_tui();
		// 	NEED_RENDER.store(1, Ordering::Relaxed);
		// 	succ!()
		// }

		// Global keyboard shortcuts - check if any registered shortcut matches
		let pressed_key = format_key_event(&key);
		let mappings = &self.app.bridge.chat_state.menu.keyboard_mappings;

		// Check each action to see if its shortcut matches
		for action in MenuAction::all_actions() {
			let shortcut = mappings.get(action);

			// Handle shortcuts with "or" (e.g., "0 or Ctrl+P")
			let matches = if shortcut.contains(" or ") {
				shortcut.split(" or ").any(|s| s.trim() == pressed_key)
			} else {
				shortcut == pressed_key
			};

			if matches {
				let submenu_index = match action {
					MenuAction::ContextControlPanel => None, // Special case - just toggle menu
					MenuAction::Theme => Some(0),
					MenuAction::KeyboardShortcuts => Some(1),
					MenuAction::Providers => Some(2),
					MenuAction::PluginsApps => Some(3),
					MenuAction::Skills => Some(4),
					MenuAction::Sandbox => Some(5),
					MenuAction::WebSearch => Some(6),
					MenuAction::McpServers => Some(7),
					MenuAction::MemoryHistory => Some(8),
					MenuAction::MultiAgent => Some(9),
					MenuAction::Notifications => Some(10),
					MenuAction::VoiceRealtime => Some(11),
					MenuAction::ImageVision => Some(12),
					MenuAction::Profiles => Some(13),
					MenuAction::Worktree => Some(14),
					MenuAction::Authentication => Some(15),
					MenuAction::NetworkProxy => Some(16),
					MenuAction::HooksEvents => Some(17),
					MenuAction::SessionResume => Some(18),
					MenuAction::ApprovalPolicy => Some(19),
					MenuAction::ShellEnvironment => Some(20),
					MenuAction::ExecutionRules => Some(21),
					MenuAction::ProjectTrust => Some(22),
					MenuAction::DeveloperInstructions => Some(23),
					MenuAction::FeatureFlags => Some(24),
				};

				// Check if menu is already open with this submenu
				let is_same_submenu = if let Some(idx) = submenu_index {
					self.app.bridge.chat_state.show_tachyon_menu
						&& self.app.bridge.chat_state.menu.current_submenu == Some(idx)
						&& self.app.bridge.chat_state.menu.opened_directly
				} else {
					// For ContextControlPanel, check if menu is open at main level
					self.app.bridge.chat_state.show_tachyon_menu
						&& self.app.bridge.chat_state.menu.current_submenu.is_none()
				};

				if is_same_submenu {
					// Toggle off - close the menu
					self.app.bridge.chat_state.menu_is_closing = true;
					self.app.bridge.chat_state.menu.pick_closing_effect();
				} else {
					// Open menu if not already open
					if !self.app.bridge.chat_state.show_tachyon_menu {
						self.app.bridge.chat_state.menu_is_closing = false;
						self.app.bridge.chat_state.show_tachyon_menu = true;
						self.app.bridge.chat_state.menu.pick_opening_effect();
					}

					// Navigate to the submenu directly (without "Back" button)
					if let Some(idx) = submenu_index {
						self.app.bridge.chat_state.menu.enter_submenu_directly(idx);
					} else {
						// ContextControlPanel - go to main menu
						self.app.bridge.chat_state.menu.go_back_to_main();
					}
				}

				NEED_RENDER.store(1, Ordering::Relaxed);
				succ!()
			}
		}

		// Handle chat input when in Chat mode or FilePicker mode (chat input is visible)
		if self.app.bridge.mode == crate::AppMode::Chat
			|| self.app.bridge.mode == crate::AppMode::FilePicker
		{
			// CRITICAL: Handle Ctrl+C to return to splash or exit
			// If we have messages (in chat mode), play outro animation to return to splash
			// If no messages (splash screen), show train farewell and exit
			if key.code == KeyCode::Char('c') && key.modifiers.contains(KeyModifiers::CONTROL) {
				if !self.app.bridge.chat_state.messages.is_empty() {
					// We have messages - play outro animation to return to splash
					self.app.bridge.chat_state.play_outro_animation();
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				} else {
					// No messages (splash screen) - exit with train animation
					crate::exit_animation::show_train_farewell();
					std::process::exit(0);
				}
			}

			// CRITICAL: Handle Left/Right arrow keys for DX navigation BEFORE forwarding to codex
			// DX uses these for screen switching (animation carousel, file browser, etc.)
			// Codex TUI doesn't really need arrow keys, so we intercept them
			if key.modifiers.is_empty() {
				match key.code {
					KeyCode::Left => {
						// Left arrow: Go to animation carousel
						self.app.bridge.chat_state.animation_mode = true;
						// Start at first carousel animation (Matrix)
						let carousel = crate::AnimationType::carousel_animations();
						let all_animations = crate::AnimationType::all();
						if let Some(matrix_idx) = all_animations.iter().position(|a| *a == carousel[0]) {
							self.app.bridge.chat_state.current_animation_index = matrix_idx;
						}
						self.app.bridge.chat_state.animation_start_time = Some(Instant::now());
						self.app.bridge.chat_state.play_animation_sound(); // Play sound for animation
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
					KeyCode::Right => {
						// Right arrow: Go to file browser
						self.app.bridge.chat_state.animation_mode = false;
						self.app.bridge.chat_state.stop_animation_sound(); // Stop sound when leaving animations
						self.app.bridge.mode = crate::bridge::AppMode::FilePicker;
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
					_ => {}
				}
			}

			// Handle Ctrl+Super (Windows/Command/Meta) for voice mode
			// This is the primary voice input trigger that doesn't interfere with typing
			if key.code == KeyCode::Char(' ')
				&& key.modifiers.contains(KeyModifiers::CONTROL)
				&& key.modifiers.contains(KeyModifiers::SUPER)
			{
				use crossterm::event::KeyEventKind;

				if key.kind == KeyEventKind::Press || key.kind == KeyEventKind::Repeat {
					// Activate voice mode
					if !self.app.bridge.chat_state.space_held {
						self.app.bridge.chat_state.space_held = true;
						self.app.bridge.chat_state.space_hold_start = Some(Instant::now());
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				} else if key.kind == KeyEventKind::Release {
					// Deactivate voice mode
					if self.app.bridge.chat_state.space_held {
						self.app.bridge.chat_state.space_held = false;
						self.app.bridge.chat_state.space_hold_start = None;
						NEED_RENDER.store(1, Ordering::Relaxed);
					}
					succ!()
				}
			}

			// Handle Space key for voice mode - simplified hold detection (fallback)
			// Only activate if held for a longer time to avoid interfering with normal typing
			if key.code == KeyCode::Char(' ') && key.modifiers.is_empty() {
				use crossterm::event::KeyEventKind;

				let now = Instant::now();
				let is_repeat = key.kind == KeyEventKind::Repeat;
				let is_press = key.kind == KeyEventKind::Press;

				// Only activate voice mode on explicit repeat events (not timing-based)
				// This prevents interference with pasting and normal typing
				if is_repeat {
					// Key is being held! Activate voice mode (spinner)
					if !self.app.bridge.chat_state.space_held {
						// Save cursor position before reverting
						let old_cursor_pos = self.app.bridge.chat_state.input.cursor_position;
						self.app.bridge.chat_state.cursor_revert_from_pos = old_cursor_pos;

						// Remove trailing spaces that were typed during hold detection
						let mut new_pos = old_cursor_pos;
						let mut spaces_removed = 0;

						while new_pos > 0 && spaces_removed < 2 {
							let content_before = &self.app.bridge.chat_state.input.content[..new_pos];
							if content_before.ends_with(' ') {
								new_pos -= 1;
								self.app.bridge.chat_state.input.content.remove(new_pos);
								spaces_removed += 1;
							} else {
								break;
							}
						}

						if spaces_removed > 0 {
							self.app.bridge.chat_state.input.cursor_position = new_pos;
						}

						// Start cursor revert animation
						self.app.bridge.chat_state.cursor_revert_animation = true;
						self.app.bridge.chat_state.cursor_revert_start = Some(now);

						// Activate voice mode
						self.app.bridge.chat_state.space_held = true;
						self.app.bridge.chat_state.space_hold_start = Some(now);
					}
					self.app.bridge.chat_state.last_space_press = Some(now);
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!() // Don't type spaces while holding
				} else if key.kind == KeyEventKind::Release {
					// Space released - deactivate voice mode
					if self.app.bridge.chat_state.space_held {
						self.app.bridge.chat_state.space_held = false;
						self.app.bridge.chat_state.space_hold_start = None;
						self.app.bridge.chat_state.last_space_press = None;
						self.app.bridge.chat_state.cursor_revert_animation = false;
						self.app.bridge.chat_state.cursor_revert_start = None;
						NEED_RENDER.store(1, Ordering::Relaxed);
					}
					succ!()
				} else if is_press {
					// First press - type the space normally and track it
					self.app.bridge.chat_state.last_space_press = Some(now);
					let action = self.app.bridge.chat_state.input.handle_key(key);
					match action {
						InputAction::Changed => {
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}
						_ => succ!(),
					}
				} else {
					// Unknown key kind - just pass through
					succ!()
				}
			} else {
				// Any other key pressed - deactivate voice mode
				if self.app.bridge.chat_state.space_held {
					self.app.bridge.chat_state.space_held = false;
					self.app.bridge.chat_state.space_hold_start = None;
					self.app.bridge.chat_state.last_space_press = None;
					self.app.bridge.chat_state.cursor_revert_animation = false;
					self.app.bridge.chat_state.cursor_revert_start = None;
					NEED_RENDER.store(1, Ordering::Relaxed);
				}
			}

			// If voice mode is active (spinner showing), don't process any input - just return
			if self.app.bridge.chat_state.space_held {
				NEED_RENDER.store(1, Ordering::Relaxed);
				succ!()
			}

			// Handle scrolling when messages exist and input is empty
			if !self.app.bridge.chat_state.messages.is_empty()
				&& self.app.bridge.chat_state.input.content.is_empty()
			{
				match key.code {
					KeyCode::Up => {
						self.app.bridge.chat_state.chat_scroll_offset =
							self.app.bridge.chat_state.chat_scroll_offset.saturating_add(1);

						// Clamp to max scroll
						let max_scroll = self.app.bridge.chat_state.calculate_max_scroll();
						self.app.bridge.chat_state.chat_scroll_offset =
							self.app.bridge.chat_state.chat_scroll_offset.min(max_scroll);

						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
					KeyCode::Down => {
						self.app.bridge.chat_state.chat_scroll_offset =
							self.app.bridge.chat_state.chat_scroll_offset.saturating_sub(1);
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
					_ => {}
				}
			}
			// Route key to DX chat input
			let action = self.app.bridge.chat_state.input.handle_key(key);

			// After input changes, check for file paths and extract them
			if action == InputAction::Changed || action == InputAction::Pasted {
				self.check_and_extract_file_paths();
			}

			// Show notification for Ctrl+V paste
			if action == InputAction::Pasted {
				self.app.bridge.chat_state.show_toast("Ctrl+V: Text pasted".to_string());
			}

			match action {
				InputAction::Submit(msg) => {
					// Add to DX's own chat (Ollama mode)
					// Note: When Codex TUI is active, we never reach this code
					// because keys are forwarded to ChatWidget at the top of dispatch_key
					self.app.bridge.chat_state.add_user_message(msg);
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				InputAction::Exit => {
					// If we have messages (in chat mode), play outro animation to return to splash
					if !self.app.bridge.chat_state.messages.is_empty() {
						self.app.bridge.chat_state.play_outro_animation();
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					} else {
						// No messages (splash screen or other screens), show train farewell and exit
						crate::exit_animation::show_train_farewell();
						std::process::exit(0);
					}
				}
				InputAction::Changed => {
					// Auto-scroll input box if cursor goes beyond visible area
					self.update_input_scroll();
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				InputAction::Pasted => {
					// Auto-scroll input box after paste
					self.update_input_scroll();
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				InputAction::PreviousHistory | InputAction::NextHistory => {
					// TODO: Implement history navigation
					succ!()
				}
				InputAction::None => {
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
			}
		}
		// Route to yazi's normal key handling
		Router::new(self.app).route(Key::from(key))?;
		succ!();
	}

	#[inline]
	fn dispatch_mouse(&mut self, mouse: MouseEvent) -> Result<Data> {
		use crossterm::event::MouseEventKind;

		// Track mouse movement to show/hide scrollbar
		if matches!(mouse.kind, MouseEventKind::Moved) {
			self.app.bridge.chat_state.mouse_in_window = true;
		}

		// Handle menu mouse events globally when menu is visible
		if self.app.bridge.chat_state.show_tachyon_menu {
			match mouse.kind {
				MouseEventKind::Moved => {
					// Handle hover - always process and render if state changed
					if self.app.bridge.chat_state.menu.handle_mouse(mouse.column, mouse.row, false) {
						// Apply theme preview if hovering over a theme
						if let Some(theme_name) = self.app.bridge.chat_state.menu.get_hovered_theme_name() {
							self
								.app
								.bridge
								.chat_state
								.apply_theme(&theme_name, self.app.bridge.chat_state.theme_mode);
						}
					}
					NEED_RENDER.store(1, Ordering::Relaxed);
				}
				MouseEventKind::Down(_) => {
					// Check if clicking on red dot in main menu (close button)
					if !self.app.bridge.chat_state.menu.content_viewer_mode {
						let red_dot_area = self.app.bridge.chat_state.menu.window_control_area;
						// Check if clicking on the red dot
						if mouse.column == red_dot_area.x && mouse.row == red_dot_area.y {
							// Start closing animation
							self.app.bridge.chat_state.menu_is_closing = true;
							self.app.bridge.chat_state.menu.pick_closing_effect();
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}
					}

					// Check if in content viewer mode and clicking on red dot (close button)
					if self.app.bridge.chat_state.menu.content_viewer_mode {
						let red_dot_area = self.app.bridge.chat_state.menu.window_control_area;
						// Check if clicking on the red dot
						if mouse.column == red_dot_area.x && mouse.row == red_dot_area.y {
							// Start closing animation (don't call close_content_viewer yet)
							self.app.bridge.chat_state.menu_is_closing = true;
							self.app.bridge.chat_state.menu.pick_closing_effect();
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}
					}

					// Handle click - select and potentially enter submenu
					if self.app.bridge.chat_state.menu.handle_mouse(mouse.column, mouse.row, true) {
						// Check if a model is clicked
						if let Some(model_id) = self.app.bridge.chat_state.menu.get_selected_model_id() {
							// Select the model
							self.app.bridge.chat_state.select_model(&model_id);
							// Close menu with animation
							self.app.bridge.chat_state.menu_is_closing = true;
							self.app.bridge.chat_state.menu.pick_closing_effect();
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}

						// Check if toggle mode button is clicked
						if self.app.bridge.chat_state.menu.is_toggle_mode_selected() {
							// Toggle the theme mode
							self.app.bridge.chat_state.toggle_theme_mode();
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}

						// Check if toggle recording button is clicked
						if self.app.bridge.chat_state.menu.is_toggle_recording_selected() {
							// Toggle the recording mode
							self.app.bridge.chat_state.menu.toggle_recording_mode();
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}

						// Get the current theme name before selecting
						let theme_name = self.app.bridge.chat_state.menu.get_selected_theme_name();

						// Item was clicked - now select it (enter submenu or execute)
						let _should_close = !self.app.bridge.chat_state.menu.select_current_item();

						// If we were in theme submenu and clicked a theme, just close the menu
						// (theme is already applied from hover)
						if theme_name.is_some() {
							self.app.bridge.chat_state.menu_is_closing = true;
							self.app.bridge.chat_state.menu.pick_closing_effect();
						}

						NEED_RENDER.store(1, Ordering::Relaxed);
					}
				}
				MouseEventKind::ScrollUp => {
					// Scroll up (previous items)
					self.app.bridge.chat_state.menu.select_prev_menu_item();
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				MouseEventKind::ScrollDown => {
					// Scroll down (next items)
					self.app.bridge.chat_state.menu.select_next_menu_item();
					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
				_ => {}
			}
		}

		// Handle chat mode mouse events (when menu is not visible)
		if !self.app.bridge.chat_state.show_tachyon_menu {
			use crossterm::event::MouseEventKind;

			match mouse.kind {
				MouseEventKind::Down(button) => {
					// Handle right-click to populate clipboard buffer
					if matches!(button, crossterm::event::MouseButton::Right) {
						// Try to get clipboard content using cli_clipboard (same as Ctrl+V)
						if let Ok(text) = cli_clipboard::get_contents() {
							self.app.bridge.chat_state.clipboard_buffer = Some(text);
							// Show toast notification
							self.app.bridge.chat_state.show_toast("Right-click: Text ready to paste".to_string());
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}
					}

					// Handle left-click for buttons and scrollbar
					if matches!(button, crossterm::event::MouseButton::Left) {
						let col = mouse.column;
						let row = mouse.row;

						// Check if scrollbar or right side was clicked (expanded hit area)
						let scrollbar_area = self.app.bridge.chat_state.chat_scrollbar_area;
						// Expand scrollbar area to include entire right side (from scrollbar to edge)
						let expanded_scrollbar_x = scrollbar_area.x;
						if !self.app.bridge.chat_state.messages.is_empty()
							&& col >= expanded_scrollbar_x
							&& row >= scrollbar_area.y
							&& row < scrollbar_area.y + scrollbar_area.height
						{
							// Check if clicking on a message marker
							let clicked_message_index = self.find_message_marker_at_position(row);

							if let Some(msg_index) = clicked_message_index {
								// Jump to the specific message
								self.scroll_to_message(msg_index);
								NEED_RENDER.store(1, Ordering::Relaxed);
								succ!()
							} else {
								// Regular scrollbar click - calculate scroll position based on click position
								let relative_y = row.saturating_sub(scrollbar_area.y) as usize;
								let scrollbar_height = scrollbar_area.height as usize;
								let max_scroll = self.app.bridge.chat_state.calculate_max_scroll();

								// Map click position to scroll offset
								let new_offset = if scrollbar_height > 0 {
									(relative_y * max_scroll) / scrollbar_height
								} else {
									0
								};

								self.app.bridge.chat_state.chat_scroll_offset = new_offset.min(max_scroll);

								// Start dragging
								self.app.bridge.chat_state.scrollbar_dragging = true;

								NEED_RENDER.store(1, Ordering::Relaxed);
							}
							succ!()
						}

						// Check if paste button was clicked
						let paste_area = self.app.bridge.chat_state.paste_button_area;
						if self.app.bridge.chat_state.clipboard_buffer.is_some()
							&& col >= paste_area.x
							&& col < paste_area.x + paste_area.width
							&& row >= paste_area.y
							&& row < paste_area.y + paste_area.height
						{
							// Actually paste the text into the input
							if let Some(ref text) = self.app.bridge.chat_state.clipboard_buffer.clone() {
								// Sanitize: replace newlines with spaces to prevent auto-submit
								let sanitized = text.replace('\n', " ").replace('\r', "");

								// Insert at cursor position
								if self.app.bridge.chat_state.input.has_selection() {
									self.app.bridge.chat_state.input.delete_selection();
								}

								for c in sanitized.chars() {
									self.app.bridge.chat_state.input.insert_char(c);
								}

								// Clear the clipboard buffer after pasting
								self.app.bridge.chat_state.clipboard_buffer = None;
							}
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}

						// Check if file button was clicked
						let file_area = self.app.bridge.chat_state.file_button_area;
						if !self.app.bridge.chat_state.dropped_files.is_empty()
							&& col >= file_area.x
							&& col < file_area.x + file_area.width
							&& row >= file_area.y
							&& row < file_area.y + file_area.height
						{
							// Toggle attachment menu
							if self.app.bridge.chat_state.show_tachyon_menu
								&& self.app.bridge.chat_state.menu.content_viewer_mode
							{
								// Menu is already showing attachments - close it with animation
								self.app.bridge.chat_state.menu_is_closing = true;
								self.app.bridge.chat_state.menu.pick_closing_effect();
							} else {
								// Show attachment menu using the existing menu system
								let mut file_list_lines = Vec::new();
								for (i, file_path) in self.app.bridge.chat_state.dropped_files.iter().enumerate() {
									let filename = std::path::Path::new(file_path)
										.file_name()
										.and_then(|n| n.to_str())
										.unwrap_or(file_path);
									file_list_lines.push(format!("{}. {}", i + 1, filename));
								}
								let file_list = file_list_lines.join("\n");
								let title = "Attached".to_string(); // Removed "(Cancel)" text
								self.app.bridge.chat_state.menu.show_content_viewer(title, file_list);
								self.app.bridge.chat_state.show_tachyon_menu = true;
							}
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}

						// Check if path button was clicked
						let path_area = self.app.bridge.chat_state.path_button_area;
						if col >= path_area.x
							&& col < path_area.x + path_area.width
							&& row >= path_area.y
							&& row < path_area.y + path_area.height
						{
							// Toggle between Chat/Animation and FilePicker modes
							match self.app.bridge.mode {
								crate::bridge::AppMode::Chat => {
									// Remember if we were in animation mode
									self.app.bridge.previous_mode_was_animation =
										self.app.bridge.chat_state.animation_mode;

									// Exit animation mode and go to file browser
									self.app.bridge.chat_state.animation_mode = false;
									self.app.bridge.mode = crate::bridge::AppMode::FilePicker;
								}
								crate::bridge::AppMode::FilePicker => {
									// Return to previous state (animation or chat)
									if self.app.bridge.previous_mode_was_animation {
										self.app.bridge.chat_state.animation_mode = true;
									}
									self.app.bridge.mode = crate::bridge::AppMode::Chat;
								}
							}

							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}

						// Check if model button was clicked
						let model_area = self.app.bridge.chat_state.model_button_area;
						if col >= model_area.x
							&& col < model_area.x + model_area.width
							&& row >= model_area.y
							&& row < model_area.y + model_area.height
						{
							// Toggle model picker
							self.app.bridge.chat_state.toggle_model_picker();
							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}

						// Check if clicking inside model picker
						if self.app.bridge.chat_state.show_model_picker {
							use crate::models::get_available_models;

							// Get terminal size
							let terminal_size = crossterm::terminal::size().unwrap_or((80, 24));
							let term_width = terminal_size.0;
							let term_height = terminal_size.1;

							// Calculate menu area (same as in render_model_picker)
							let models = get_available_models();
							let menu_width = 60;
							let menu_height = (models.len() as u16 + 4).min(term_height.saturating_sub(4));
							let menu_x = term_width.saturating_sub(menu_width) / 2;
							let menu_y = term_height.saturating_sub(menu_height) / 2;

							// Check if click is inside menu
							if col >= menu_x
								&& col < menu_x + menu_width
								&& row >= menu_y
								&& row < menu_y + menu_height
							{
								// Calculate which model was clicked (accounting for borders and sections)
								let relative_row = row.saturating_sub(menu_y + 1); // +1 for top border

								// Map row to model index
								// Row 0: "▼ Local Models"
								// Row 1+: Local models
								// Then blank line
								// Then "▼ Codex Models"
								// Then Codex models

								let local_models: Vec<_> = models
									.iter()
									.filter(|m| matches!(m.provider, crate::models::ModelProvider::Local))
									.collect();
								let codex_models: Vec<_> = models
									.iter()
									.filter(|m| matches!(m.provider, crate::models::ModelProvider::Codex))
									.collect();

								let local_section_end = 1 + local_models.len();
								let codex_section_start = local_section_end + 2; // +2 for blank line and header

								if relative_row > 0 && relative_row <= local_models.len() as u16 {
									// Clicked on a local model
									let model_index = (relative_row - 1) as usize;
									if let Some(model) = local_models.get(model_index) {
										self.app.bridge.chat_state.select_model(&model.id);
										NEED_RENDER.store(1, Ordering::Relaxed);
										succ!()
									}
								} else if relative_row >= codex_section_start as u16 {
									// Clicked on a Codex model
									let model_index = (relative_row - codex_section_start as u16) as usize;
									if let Some(model) = codex_models.get(model_index) {
										self.app.bridge.chat_state.select_model(&model.id);
										NEED_RENDER.store(1, Ordering::Relaxed);
										succ!()
									}
								}
							} else {
								// Clicked outside menu - close it
								self.app.bridge.chat_state.show_model_picker = false;
								NEED_RENDER.store(1, Ordering::Relaxed);
								succ!()
							}
						}
					}
				}
				MouseEventKind::ScrollUp => {
					// Check if scrolling over input area
					let input_area = self.app.bridge.chat_state.input_area;
					if mouse.column >= input_area.x
						&& mouse.column < input_area.x + input_area.width
						&& mouse.row >= input_area.y
						&& mouse.row < input_area.y + input_area.height
					{
						// Scroll up in input box
						self.app.bridge.chat_state.input_scroll_offset =
							self.app.bridge.chat_state.input_scroll_offset.saturating_sub(1);
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					} else if !self.app.bridge.chat_state.messages.is_empty() {
						// Scroll up in chat messages (decrease offset to show newer messages)
						self.app.bridge.chat_state.chat_scroll_offset =
							self.app.bridge.chat_state.chat_scroll_offset.saturating_sub(1);
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
				}
				MouseEventKind::ScrollDown => {
					// Check if scrolling over input area
					let input_area = self.app.bridge.chat_state.input_area;
					if mouse.column >= input_area.x
						&& mouse.column < input_area.x + input_area.width
						&& mouse.row >= input_area.y
						&& mouse.row < input_area.y + input_area.height
					{
						// Scroll down in input box
						// Calculate max scroll
						let text_width = input_area.width.saturating_sub(4) as usize;
						if text_width > 0 {
							let mut total_lines = 0;
							for line in self.app.bridge.chat_state.input.content.lines() {
								if line.is_empty() {
									total_lines += 1;
								} else {
									let chars = line.chars().count();
									total_lines += (chars + text_width - 1) / text_width;
								}
							}
							let viewport_height = input_area.height.saturating_sub(2) as usize;
							let max_scroll = total_lines.saturating_sub(viewport_height);

							self.app.bridge.chat_state.input_scroll_offset =
								(self.app.bridge.chat_state.input_scroll_offset + 1).min(max_scroll);
						}
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					} else {
						// Scroll down in chat messages (increase offset to show older messages)
						if !self.app.bridge.chat_state.messages.is_empty() {
							self.app.bridge.chat_state.chat_scroll_offset =
								self.app.bridge.chat_state.chat_scroll_offset.saturating_add(1);

							// Clamp to max scroll
							let max_scroll = self.app.bridge.chat_state.calculate_max_scroll();
							self.app.bridge.chat_state.chat_scroll_offset =
								self.app.bridge.chat_state.chat_scroll_offset.min(max_scroll);

							NEED_RENDER.store(1, Ordering::Relaxed);
							succ!()
						}
					}
				}
				MouseEventKind::Up(_) => {
					// Stop dragging when mouse button is released
					if self.app.bridge.chat_state.scrollbar_dragging {
						self.app.bridge.chat_state.scrollbar_dragging = false;
						NEED_RENDER.store(1, Ordering::Relaxed);
					}
				}
				MouseEventKind::Drag(button) => {
					// Handle scrollbar dragging
					if matches!(button, crossterm::event::MouseButton::Left)
						&& self.app.bridge.chat_state.scrollbar_dragging
						&& !self.app.bridge.chat_state.messages.is_empty()
					{
						let row = mouse.row;
						let scrollbar_area = self.app.bridge.chat_state.chat_scrollbar_area;

						// Calculate scroll position based on drag position
						// Allow dragging even if mouse moves outside scrollbar horizontally
						let relative_y = row.saturating_sub(scrollbar_area.y) as usize;
						let scrollbar_height = scrollbar_area.height as usize;
						let max_scroll = self.app.bridge.chat_state.calculate_max_scroll();

						// Map drag position to scroll offset
						let new_offset =
							if scrollbar_height > 0 { (relative_y * max_scroll) / scrollbar_height } else { 0 };

						self.app.bridge.chat_state.chat_scroll_offset = new_offset.min(max_scroll);
						NEED_RENDER.store(1, Ordering::Relaxed);
						succ!()
					}
				}
				_ => {}
			}
		}

		let cx = &mut Ctx::active(&mut self.app.core, &mut self.app.term);
		act!(app:mouse, cx, mouse)
	}

	#[inline]
	fn dispatch_resize(&mut self) -> Result<Data> {
		let cx = &mut Ctx::active(&mut self.app.core, &mut self.app.term);
		act!(app:resize, cx, crate::Root::reflow as fn(_) -> _)
	}

	#[inline]
	fn dispatch_focus(&mut self) -> Result<Data> {
		// Terminal window gained focus - update input focus state
		self.app.bridge.chat_state.input_focused = true;
		self.app.bridge.chat_state.received_first_focus = true; // Mark that we've received first focus
		NEED_RENDER.store(1, Ordering::Relaxed);

		let cx = &mut Ctx::active(&mut self.app.core, &mut self.app.term);
		act!(app:focus, cx)
	}

	#[inline]
	fn dispatch_blur(&mut self) -> Result<Data> {
		// Terminal window lost focus - update input focus state
		self.app.bridge.chat_state.input_focused = false;
		NEED_RENDER.store(1, Ordering::Relaxed);
		succ!()
	}

	#[inline]
	fn dispatch_paste(&mut self, str: String) -> Result<Data> {
		// Check if the pasted content contains file paths (Windows, Linux, or macOS)
		// Windows: C:\path\to\file or file:///C:/path/to/file
		// Linux/macOS: /path/to/file or file:///path/to/file
		// Also check for common file extensions
		let is_file_path = str.starts_with("file://")
			|| str.starts_with('/')
			|| (str.len() > 3 && str.chars().nth(1) == Some(':') && (str.chars().nth(2) == Some('\\') || str.chars().nth(2) == Some('/')))
			|| str.contains(":\\") // Windows path like C:\
			|| (str.lines().count() == 1 && (
				str.ends_with(".txt") || str.ends_with(".md") || str.ends_with(".rs") ||
				str.ends_with(".toml") || str.ends_with(".json") || str.ends_with(".yaml") ||
				str.ends_with(".yml") || str.ends_with(".png") || str.ends_with(".jpg") ||
				str.ends_with(".jpeg") || str.ends_with(".gif") || str.ends_with(".pdf") ||
				str.ends_with(".doc") || str.ends_with(".docx") || str.ends_with(".zip")
			));

		// Handle paste for DX chat input (when in Chat or FilePicker mode)
		if self.app.bridge.mode == crate::AppMode::Chat
			|| self.app.bridge.mode == crate::AppMode::FilePicker
		{
			if is_file_path {
				// Parse file paths from the pasted content
				// On Windows, file drops use null bytes (\0) as separators
				// DO NOT split by newlines or backslashes - they are part of paths!
				let paths: Vec<String> = if str.contains('\0') {
					// Windows file drop - split by null bytes only
					str
						.split('\0')
						.map(|line| {
							let trimmed = line.trim();
							// Remove file:// prefix if present
							if trimmed.starts_with("file://") {
								// Handle file:///C:/path (Windows) or file:///path (Unix)
								let path = &trimmed[7..];
								// Simple URL decode: replace %20 with space
								path.replace("%20", " ")
							} else {
								trimmed.to_string()
							}
						})
						.filter(|p| !p.is_empty())
						.collect()
				} else {
					// Single file path - no splitting at all
					let trimmed = str.trim();
					let path = if trimmed.starts_with("file://") {
						// Handle file:///C:/path (Windows) or file:///path (Unix)
						let path = &trimmed[7..];
						// Simple URL decode: replace %20 with space
						path.replace("%20", " ")
					} else {
						trimmed.to_string()
					};

					// Only add if not empty
					if path.is_empty() { vec![] } else { vec![path] }
				};

				if !paths.is_empty() {
					// ADD dropped files (allow multiple attachments) - don't check for duplicates
					for path in paths {
						self.app.bridge.chat_state.dropped_files.push(path);
					}

					// Show toast notification
					let file_count = self.app.bridge.chat_state.dropped_files.len();
					let msg = if file_count == 1 {
						format!(
							"File attached: {}",
							std::path::Path::new(&self.app.bridge.chat_state.dropped_files[0])
								.file_name()
								.and_then(|n| n.to_str())
								.unwrap_or("file")
						)
					} else {
						format!("{} files attached", file_count)
					};
					self.app.bridge.chat_state.show_toast(msg);

					NEED_RENDER.store(1, Ordering::Relaxed);
					succ!()
				}
			}

			// Not a file path - treat as regular clipboard content
			// Don't auto-paste! Just populate clipboard_buffer to show the "Paste" button
			// User must click the button to actually paste
			self.app.bridge.chat_state.clipboard_buffer = Some(str.clone());

			// Show toast notification for paste
			self.app.bridge.chat_state.show_toast("Text ready to paste".to_string());

			NEED_RENDER.store(1, Ordering::Relaxed);
			succ!()
		}

		// Handle paste for file browser input (yazi)
		if self.app.core.input.visible {
			let input = &mut self.app.core.input;
			if input.mode() == InputMode::Insert {
				input.type_str(&str)?;
			} else if input.mode() == InputMode::Replace {
				input.replace_str(&str)?;
			}
		}
		succ!();
	}

	/// Find which message marker was clicked based on Y position
	fn find_message_marker_at_position(&self, click_y: u16) -> Option<usize> {
		let scrollbar_area = self.app.bridge.chat_state.chat_scrollbar_area;
		let messages = &self.app.bridge.chat_state.messages;

		if messages.is_empty() {
			return None;
		}

		// Calculate cumulative heights for each message (same logic as rendering)
		let mut cumulative_heights = Vec::new();
		let mut current_height = 0;

		for msg in messages.iter() {
			cumulative_heights.push(current_height);

			let content_lines = if msg.content.is_empty() { 1 } else { msg.content.lines().count() };

			let msg_height = match msg.role {
				crate::components::MessageRole::User => content_lines + 3 + 1,
				crate::components::MessageRole::Assistant => content_lines + 1 + 1,
			};

			current_height += msg_height;
		}

		let total_height = current_height;
		let scrollbar_height = scrollbar_area.height as usize;

		// Check each message marker position
		for (idx, &msg_pos) in cumulative_heights.iter().enumerate() {
			let marker_y = if total_height > 0 { (msg_pos * scrollbar_height) / total_height } else { 0 };

			let y = scrollbar_area.y + marker_y as u16;

			// Check if click is within 1 row of the marker
			if click_y >= y.saturating_sub(1) && click_y <= y.saturating_add(1) {
				return Some(idx);
			}
		}

		None
	}

	/// Scroll to show a specific message
	fn scroll_to_message(&mut self, message_index: usize) {
		let messages = &self.app.bridge.chat_state.messages;

		if message_index >= messages.len() {
			return;
		}

		// Calculate the cumulative height up to this message
		let mut target_offset = 0;

		for (idx, msg) in messages.iter().enumerate() {
			if idx >= message_index {
				break;
			}

			let content_lines = if msg.content.is_empty() { 1 } else { msg.content.lines().count() };

			let msg_height = match msg.role {
				crate::components::MessageRole::User => content_lines + 3 + 1,
				crate::components::MessageRole::Assistant => content_lines + 1 + 1,
			};

			target_offset += msg_height;
		}

		// Set scroll offset to show this message at the top
		let max_scroll = self.app.bridge.chat_state.calculate_max_scroll();
		self.app.bridge.chat_state.chat_scroll_offset = target_offset.min(max_scroll);
	}

	/// Update input box scroll offset to keep cursor visible
	fn update_input_scroll(&mut self) {
		let input_area = self.app.bridge.chat_state.input_area;
		let text_width = input_area.width.saturating_sub(4) as usize; // Subtract borders and padding
		if text_width == 0 {
			return;
		}

		// Calculate which line the cursor is on
		let content = &self.app.bridge.chat_state.input.content;
		let cursor_pos = self.app.bridge.chat_state.input.cursor_position;

		let mut total_lines = 0;
		let mut cursor_line = 0;
		let mut char_count = 0;

		for line in content.lines() {
			if line.is_empty() {
				if char_count <= cursor_pos && cursor_pos <= char_count + 1 {
					cursor_line = total_lines;
				}
				total_lines += 1;
				char_count += 1; // Account for newline
			} else {
				let line_chars = line.chars().count();
				let wrapped_line_count = (line_chars + text_width - 1) / text_width;

				for wrap_idx in 0..wrapped_line_count {
					let line_start = char_count + wrap_idx * text_width;
					let line_end = (char_count + (wrap_idx + 1) * text_width).min(char_count + line_chars);

					if cursor_pos >= line_start && cursor_pos <= line_end {
						cursor_line = total_lines;
					}
					total_lines += 1;
				}

				char_count += line_chars + 1; // +1 for newline
			}
		}

		// Adjust scroll offset to keep cursor visible
		let viewport_height = input_area.height.saturating_sub(2) as usize; // Subtract borders
		let current_offset = self.app.bridge.chat_state.input_scroll_offset;

		if cursor_line < current_offset {
			// Cursor is above visible area, scroll up
			self.app.bridge.chat_state.input_scroll_offset = cursor_line;
		} else if cursor_line >= current_offset + viewport_height {
			// Cursor is below visible area, scroll down
			self.app.bridge.chat_state.input_scroll_offset =
				cursor_line.saturating_sub(viewport_height - 1);
		}
	}

	#[inline]
	fn dispatch_timer(&mut self) -> Result<Data> {
		// Timer tick for animations - just trigger a render
		// The effects are time-based and will automatically show updated colors

		// Update chat state (process LLM responses)
		self.app.bridge.chat_state.update();

		// Update splash font cycling (every 5 seconds)
		// Cycle fonts when in animation mode on Splash screen OR when showing splash in chat mode
		if self.app.bridge.chat_state.last_font_change.elapsed() >= Duration::from_secs(5) {
			let should_cycle = if self.app.bridge.chat_state.animation_mode {
				let animations = crate::AnimationType::all();
				let current_anim = animations[self.app.bridge.chat_state.current_animation_index];
				current_anim == crate::AnimationType::Splash
			} else {
				// In normal chat mode, cycle if showing splash (no messages)
				self.app.bridge.chat_state.messages.is_empty()
			};

			if should_cycle {
				self.app.bridge.chat_state.splash_font_index =
					(self.app.bridge.chat_state.splash_font_index + 1) % 113; // 113 valid fonts
				self.app.bridge.chat_state.last_font_change = Instant::now();
			}
		}

		// Update Menu timing
		let elapsed = self.app.bridge.chat_state.last_frame_instant.elapsed();
		self.app.bridge.chat_state.menu.update(elapsed);
		self.app.bridge.chat_state.last_frame_instant = Instant::now();

		NEED_RENDER.store(1, Ordering::Relaxed);
		succ!();
	}

	/// Check if input contains file paths and extract them
	fn check_and_extract_file_paths(&mut self) {
		let input_content = self.app.bridge.chat_state.input.content.clone();

		// Skip if input is empty
		if input_content.trim().is_empty() {
			return;
		}

		// Check if the input looks like a COMPLETE file path
		// Must have a file extension (complete path)
		let has_extension = input_content.ends_with(".txt")
			|| input_content.ends_with(".md")
			|| input_content.ends_with(".rs")
			|| input_content.ends_with(".toml")
			|| input_content.ends_with(".json")
			|| input_content.ends_with(".yaml")
			|| input_content.ends_with(".yml")
			|| input_content.ends_with(".png")
			|| input_content.ends_with(".jpg")
			|| input_content.ends_with(".jpeg")
			|| input_content.ends_with(".gif")
			|| input_content.ends_with(".pdf")
			|| input_content.ends_with(".doc")
			|| input_content.ends_with(".docx")
			|| input_content.ends_with(".zip");

		// Only process if it has an extension AND looks like a path
		let is_file_path = has_extension
			&& (input_content.starts_with("file://")
				|| input_content.starts_with('/')
				|| input_content.contains(":\\") // Windows path like C:\ or f:\
				|| (input_content.len() > 3
					&& input_content.chars().nth(1) == Some(':')
					&& (input_content.chars().nth(2) == Some('\\')
						|| input_content.chars().nth(2) == Some('/'))));

		if is_file_path {
			// Extract the file path
			let path = if input_content.starts_with("file://") {
				// Handle file:///C:/path (Windows) or file:///path (Unix)
				let path = &input_content[7..];
				// Simple URL decode: replace %20 with space
				path.replace("%20", " ")
			} else {
				input_content.trim().to_string()
			};

			// ADD to dropped_files list (allow multiple files) - don't check for duplicates
			// This allows adding the same file multiple times if needed
			self.app.bridge.chat_state.dropped_files.push(path.clone());

			// Show toast notification
			let filename =
				std::path::Path::new(&path).file_name().and_then(|n| n.to_str()).unwrap_or("file");
			let file_count = self.app.bridge.chat_state.dropped_files.len();
			self
				.app
				.bridge
				.chat_state
				.show_toast(format!("File {} attached ({} total)", filename, file_count));

			// Clear the input completely
			self.app.bridge.chat_state.input.content.clear();
			self.app.bridge.chat_state.input.cursor_position = 0;
			self.app.bridge.chat_state.input.scroll_offset = 0;
			self.app.bridge.chat_state.input.clear_selection();

			NEED_RENDER.store(1, Ordering::Relaxed);
		}
	}
}
